#include <iostream>
#include <openssl/bio.h>
#include <openssl/ssl.h>
#include <signal.h>
#include <cstring>
#include <chrono>
#include <functional>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <fcntl.h>