#include <iostream>
#include <wolfssl/options.h>
#include <wolfssl/ssl.h>
#include <wolfssl/wolfcrypt/coding.h>
#include <wolfssl/wolfcrypt/sha.h>
#include <wolfssl/wolfcrypt/memory.h>
#include <signal.h>
#include <cstring>
#include <chrono>
#include <functional>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <fcntl.h>